apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-poc-weather-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-poc-weather-java
  template:
    metadata:
      labels:
        app: grpc-poc-weather-java
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: grpc-poc-weather-java
          image: alinflorin/grpc-poc-weather-java:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "64Mi"
              cpu: "4m"
            limits:
              memory: "64Mi"
              cpu: "4m"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-poc-weather-java
spec:
  selector:
    app: grpc-poc-weather-java
  ports:
    - port: 9090
      targetPort: 9090
      name: http